### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by baubrey91** [CodePathDreamTeam/GroupProject#12]
- [ ] Main tasks
   - [x] To - Do list in table view
   - [x] Pull down to add new item
   - [x] Pinch to insert new item
   - [x] Swipe left to delete
   - [x] Swipe right to cross out
   - [x] After item is crossed out, move to bottom
   - [ ] add new item button
   - [ ] adjust UI
